# Site settings
url: "https://www.walkercraig.com"
baseurl: ''
production_url: 'https://walkercraig.github.io/'
name: 'Craig Walker'
description: 
meta_description: 
logo:
# Author image is used in site sidebar and greetings in the home page hero text
author:
  image: 'cwprofilecrop.png'
  greetings: "Hello & Welcome"
favicon: '/favicon.ico'
disqus: 
mailchimp_url: '//walkercraig.us11.list-manage.com/subscribe/post?u=b845f7d1807ad41b6c0437990&amp;id=7bd2f97cd8'
# Add your GA Tracking Id
ga_analytics: G-7Z1MEJ4574

# Contact form settings
email: mail@walkercraig.com
contact_page_description: "Feel free to contact Craig with any questions, concerns, or work related inquiries. You may also reach him by sending an email direct to the following address: mail at walkercraig dot com."
thankyou_page_description: "Your message has been successfully sent. We will contact you soon!"

# Social links
twitter: 'wlkrcrg'
facebook: 'wlkrcrg'
instagram: 'wlkrcrg'

# Navigation
navigation:
  - text: Home
    url: /
  - text: About
    url: /about
  - text: Letters
    url: /tags/index.html#Letters
  - text: Poems
    url: /tags/index.html#Poems
  - text: Songs
    url: /tags/index.html#Songs
  - text: Commentary
    url: /tags/index.html#Commentary
  - text: Photos
    url: https://www.instagram.com/wlkrcrg
  - text: Organizations
    url: /organizations
  - text: Contact
    url: /contact
  - text: Support
    url: https://donate.stripe.com/cNi14ocTk4je8p4gwF38403
  - text: Search
    url: /search

# Required Plugins
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme

# Pagination
paginate: 7
paginate_path: /page:num/

# Permalinks
permalink: /:title/

# Other
markdown: kramdown
kramdown:
  input: GFM          # lets you keep GitHub-style tables & fences
  footnote_nr: 1      # optional – first number in the series

# Sass
sass:
  sass_dir: _sass
  style: compressed

remote_theme: royce
